export class ScalarPromptTemplates {
    static getOpenAPITemplate(): string {
        return `
You are a technical writer specialized in API documentation. You have been given a professional OpenAPI specification generated by Scalar from a TypeScript project.

Your goal is to create comprehensive, user-friendly documentation that enhances the technical OpenAPI spec with:

🎯 **Enhanced Documentation Requirements**

**API Overview**
- Create a clear, business-focused description of what this API does
- Explain the main use cases and workflows
- Add getting started guide for developers

**Endpoint Documentation**
- Transform technical OpenAPI data into developer-friendly explanations
- Add practical examples and use cases
- Include common error scenarios and troubleshooting

**Code Examples**
- Provide working code examples in multiple languages (TypeScript, JavaScript, cURL, Python)
- Show real-world usage patterns
- Include authentication examples

**Integration Guide**
- Explain how to integrate with this API
- Provide SDK examples if applicable
- Include rate limiting and best practices

**Error Handling**
- Document common error responses
- Provide troubleshooting guides
- Include status code explanations

---

## OpenAPI Specification Data:
\`\`\`json
{{ANALYSIS_DATA}}
\`\`\`

Generate professional, comprehensive documentation that transforms this technical specification into developer-friendly content.
`
    }

    static buildOpenAPIPrompt(analysisData: any): string {
        const template = this.getOpenAPITemplate()
        return template.replace(
            '{{ANALYSIS_DATA}}',
            JSON.stringify(analysisData, null, 2)
        )
    }

    static getChunkedOpenAPITemplate(): string {
        return `
You are a technical writer creating focused documentation for a specific API module. You have been given OpenAPI specification data for a single module/controller.

Your goal is to create comprehensive, module-specific documentation that includes:

🎯 **Module Documentation Requirements**

**Module Overview**
- Clear description of what this module/controller does
- Business context and use cases
- Key features and capabilities

**Endpoint Documentation**
- Detailed explanation of each endpoint
- Request/response examples
- Parameter descriptions
- Error handling

**Code Examples**
- Working examples in TypeScript/JavaScript
- cURL examples for testing
- Integration patterns

**Data Models**
- Type definitions and schemas
- Validation rules
- Example payloads

---

## Module OpenAPI Data:
\`\`\`json
{{ANALYSIS_DATA}}
\`\`\`

Generate focused, professional documentation for this specific module.
`
    }

    static buildChunkedOpenAPIPrompt(analysisData: any): string {
        const template = this.getChunkedOpenAPITemplate()
        return template.replace(
            '{{ANALYSIS_DATA}}',
            JSON.stringify(analysisData, null, 2)
        )
    }
}
